double hdelta_min = -8;
double hdelta_max = 8;
double pdelta_min = -10;
double pdelta_max = 20;
double hms_xptar_min = -0.06;
double hms_xptar_max = 0.06;
double hms_yptar_min = -0.022;
double hms_yptar_max = 0.022;
double shms_xptar_min = -0.045;
double shms_xptar_max = 0.045;
double shms_yptar_min = -0.028;
double shms_yptar_max = 0.028;
double nbin = 20;
double binlo = 0;
double binhi = 1;
Double_t pionmass   = 0.1395701835;   
Double_t protonmass = 0.93827231;
double Emiss,Weight,normwt,normwt_sig,spdelta,z,sighad,hsdelta,theta,mom,ptsquare,pt2calc,ptcalc;
double nu,q,pm,hxptar,hyptar,pxptar,pyptar,mx2,xbj,w,W2,w2,pt,Q2,phi;
Bool_t acceptance_cut_coin;
Bool_t central_hole,right_or_left_of_hole,remove_region;
double xathgcer,yathgcer,ptrack_x_fp,ptrack_xp_fp,ptrack_y_fp,ptrack_yp_fp ;
double htrack_x_fp,htrack_xp_fp,htrack_y_fp,htrack_yp_fp ;

double xatpreshower, yatpreshower, xatshower, yatshower,xatpreshowerback , yatpreshowerback, xatshowerback, yatshowerback, Epi, zhad, Mx2,xataero,yataero;
Bool_t peter_all_geom_cut,  pcal_geom_cut_hem,  paero_geom_cut,hcal_geom_cut,hms_dc_fp_cut;
Bool_t  hms_hodo_cut, pcal_geom_cut, shms_dc_fp_cut, hourglass_cut, geom_cut_and_hgcer_cut;
Double_t xathhodo,xatpcal,yatpcal,xathcal,yathcal;
Bool_t ptcut_big,ptcut_small; 

double hcal_1pr_zpos = 338.69;
double hcal_2ta_zpos = 349.69;
double hcal_3ta_zpos = 360.69;
double hcal_4ta_zpos = 371.69;
double hcal_left     =  35.00;
double hcal_right    = -35.00;
double hcal_top      = -69.66;
double hcal_bottom   =  60.34;
double scal_1pr_zpos = 292.6;
double scal_2ta_zpos = 306.4;
double scal_3ta_zpos = 323.7;
double scal_4ta_zpos = 341.0;
double scal_left     =  63.00;
double scal_right    = -63.00;
double scal_top      = -70.00;
double scal_bottom   =  70.00;
double new_x;
double new_z;
